openapi: '3.0.0'
info:
  version: 1.0.0
  title: Wealth API
servers:
  - url: /api
paths:
  /users:
    post:
      summary: Create a user
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              required:
                - name
                - email
                - investingExperienceLevel
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                investingExperienceLevel:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /users/verify:
    post:
      summary: Verify an email exists in database
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              required:
                - email
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /portfolios:
    get:
      summary: Fetch all users portfolios
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
    post:
      summary: Create a new portfolio
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              required:
                - public
                - name
              properties:
                name:
                  type: string
                public:
                  type: boolean
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /portfolios/{portfolioID}:
    get:
      summary: Fetch a portfolio
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /portfolios/{portfolioID}/stocks:
    get:
      summary: Fetch a portfolio's stocks
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /portfolios/{portfolioID}/crypto:
    get:
      summary: Fetch a portfolio's crypto
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /portfolios/{portfolioID}/real-estate:
    get:
      summary: Fetch a portfolio's real estate
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /portfolios/{portfolioID}/customs:
    get:
      summary: Fetch a portfolio's custom assets
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /portfolios/{portfolioID}/cash:
    get:
      summary: Fetch a portfolio's cash
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /positions/stock:
    post:
      summary: Add a stock to a portfolio
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              required:
                - portfolioID
                - symbol
                - companyName
                - quantity
                - costBasis
              properties:
                portfolioID:
                  type: string
                symbol:
                  type: string
                companyName:
                  type: string
                quantity:
                  type: number
                costBasis:
                  type: number
                note:
                  type: string
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /positions/crypto:
    post:
      summary: Add crypto to a portfolio
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              required:
                - portfolioID
                - symbol
                - coinName
                - quantity
                - costBasis
              properties:
                portfolioID:
                  type: string
                symbol:
                  type: string
                coinName:
                  type: string
                quantity:
                  type: number
                costBasis:
                  type: number
                note:
                  type: string
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /positions/real-estate:
    post:
      summary: Add real estate to a portfolio
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              required:
                - portfolioID
                - propertyValue
                - propertyType
                - estimatedAppreciationRate
              properties:
                portfolioID:
                  type: string
                propertyValue:
                  type: number
                propertyType:
                  type: string
                estimatedAppreciationRate:
                  type: number
                address:
                  type: string
                note:
                  type: string
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /positions/cash:
    post:
      summary: Add cash estate to a portfolio
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              required:
                - portfolioID
                - accountName
                - amount
              properties:
                portfolioID:
                  type: string
                accountName:
                  type: string
                amount:
                  type: number
                note:
                  type: string
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
  /positions/custom:
    post:
      summary: Add custom asset to a portfolio
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              required:
                - portfolioID
                - value
                - assetName
              properties:
                portfolioID:
                  type: string
                assetName:
                  type: string
                value:
                  type: number
                note:
                  type: string
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
