openapi: '3.0.0'
info:
  version: 1.0.0
  title: Wealth API
servers:
  - url: /api
paths:
  /users:
    post:
      summary: Create a user
      requestBody:
        content:
          application/json:
            schema:
              required:
                - name
                - email
                - investingExperienceLevel
                - password
      responses:
        '200':
          description: Valid request
          content:
            application/json:
              schema:
                type: object
